# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{earth}
  s.version = "0.3.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere", "Derek Kastner", "Andy Rossmeissl"]
  s.date = %q{2011-01-11}
  s.description = %q{An earth-simulation environment with ActiveRecord models and data}
  s.email = %q{andy@rossmeissl.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "LICENSE-PREAMBLE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "lib/earth.rb",
     "lib/earth/active_record_ext.rb",
     "lib/earth/air.rb",
     "lib/earth/air/aircraft.rb",
     "lib/earth/air/aircraft/data_miner.rb",
     "lib/earth/air/aircraft_class.rb",
     "lib/earth/air/aircraft_class/data_miner.rb",
     "lib/earth/air/aircraft_manufacturer.rb",
     "lib/earth/air/aircraft_manufacturer/data_miner.rb",
     "lib/earth/air/airline.rb",
     "lib/earth/air/airline/data_miner.rb",
     "lib/earth/air/airport.rb",
     "lib/earth/air/airport/data_miner.rb",
     "lib/earth/air/data_miner.rb",
     "lib/earth/air/flight_distance_class.rb",
     "lib/earth/air/flight_distance_class/data_miner.rb",
     "lib/earth/air/flight_fuel_type.rb",
     "lib/earth/air/flight_fuel_type/data_miner.rb",
     "lib/earth/air/flight_seat_class.rb",
     "lib/earth/air/flight_seat_class/data_miner.rb",
     "lib/earth/air/flight_segment.rb",
     "lib/earth/air/flight_segment/data_miner.rb",
     "lib/earth/all.rb",
     "lib/earth/automobile.rb",
     "lib/earth/automobile/automobile_fuel_type.rb",
     "lib/earth/automobile/automobile_fuel_type/data_miner.rb",
     "lib/earth/automobile/automobile_make.rb",
     "lib/earth/automobile/automobile_make/data_miner.rb",
     "lib/earth/automobile/automobile_make_fleet_year.rb",
     "lib/earth/automobile/automobile_make_fleet_year/data_miner.rb",
     "lib/earth/automobile/automobile_make_model.rb",
     "lib/earth/automobile/automobile_make_model/data_miner.rb",
     "lib/earth/automobile/automobile_make_model_year.rb",
     "lib/earth/automobile/automobile_make_model_year/data_miner.rb",
     "lib/earth/automobile/automobile_make_model_year_variant.rb",
     "lib/earth/automobile/automobile_make_model_year_variant/data_miner.rb",
     "lib/earth/automobile/automobile_make_year.rb",
     "lib/earth/automobile/automobile_make_year/data_miner.rb",
     "lib/earth/automobile/automobile_size_class.rb",
     "lib/earth/automobile/automobile_size_class/data_miner.rb",
     "lib/earth/automobile/data_miner.rb",
     "lib/earth/base.rb",
     "lib/earth/bus.rb",
     "lib/earth/bus/bus_class.rb",
     "lib/earth/bus/bus_class/data_miner.rb",
     "lib/earth/bus/data_miner.rb",
     "lib/earth/conversions_ext.rb",
     "lib/earth/data_miner.rb",
     "lib/earth/diet.rb",
     "lib/earth/diet/data_miner.rb",
     "lib/earth/diet/diet_class.rb",
     "lib/earth/diet/diet_class/data_miner.rb",
     "lib/earth/diet/food_group.rb",
     "lib/earth/diet/food_group/data_miner.rb",
     "lib/earth/fuel.rb",
     "lib/earth/fuel/data_miner.rb",
     "lib/earth/fuel/fuel_price.rb",
     "lib/earth/fuel/fuel_price/data_miner.rb",
     "lib/earth/fuel/fuel_type.rb",
     "lib/earth/fuel/fuel_type/data_miner.rb",
     "lib/earth/hospitality.rb",
     "lib/earth/hospitality/data_miner.rb",
     "lib/earth/hospitality/lodging_class.rb",
     "lib/earth/hospitality/lodging_class/data_miner.rb",
     "lib/earth/industry.rb",
     "lib/earth/industry/industry.rb",
     "lib/earth/industry/industry_product.rb",
     "lib/earth/industry/industry_product_line.rb",
     "lib/earth/industry/industry_sector.rb",
     "lib/earth/industry/merchant.rb",
     "lib/earth/industry/merchant_category.rb",
     "lib/earth/industry/merchant_category_industry.rb",
     "lib/earth/industry/product_line.rb",
     "lib/earth/industry/product_line_industry_product.rb",
     "lib/earth/industry/sector.rb",
     "lib/earth/inflectors.rb",
     "lib/earth/locality.rb",
     "lib/earth/locality/census_division.rb",
     "lib/earth/locality/census_division/data_miner.rb",
     "lib/earth/locality/census_region.rb",
     "lib/earth/locality/census_region/data_miner.rb",
     "lib/earth/locality/climate_division.rb",
     "lib/earth/locality/climate_division/data_miner.rb",
     "lib/earth/locality/country.rb",
     "lib/earth/locality/country/data_miner.rb",
     "lib/earth/locality/data_miner.rb",
     "lib/earth/locality/egrid_region.rb",
     "lib/earth/locality/egrid_region/data_miner.rb",
     "lib/earth/locality/egrid_subregion.rb",
     "lib/earth/locality/egrid_subregion/data_miner.rb",
     "lib/earth/locality/petroleum_administration_for_defense_district.rb",
     "lib/earth/locality/petroleum_administration_for_defense_district/data_miner.rb",
     "lib/earth/locality/state.rb",
     "lib/earth/locality/state/data_miner.rb",
     "lib/earth/locality/urbanity.rb",
     "lib/earth/locality/urbanity/data_miner.rb",
     "lib/earth/locality/zip_code.rb",
     "lib/earth/locality/zip_code/data_miner.rb",
     "lib/earth/pet.rb",
     "lib/earth/pet/breed.rb",
     "lib/earth/pet/breed/data_miner.rb",
     "lib/earth/pet/breed_gender.rb",
     "lib/earth/pet/breed_gender/data_miner.rb",
     "lib/earth/pet/data_miner.rb",
     "lib/earth/pet/gender.rb",
     "lib/earth/pet/gender/data_miner.rb",
     "lib/earth/pet/species.rb",
     "lib/earth/pet/species/data_miner.rb",
     "lib/earth/rail.rb",
     "lib/earth/rail/data_miner.rb",
     "lib/earth/rail/rail_class.rb",
     "lib/earth/rail/rail_class/data_miner.rb",
     "lib/earth/residence.rb",
     "lib/earth/residence/air_conditioner_use.rb",
     "lib/earth/residence/air_conditioner_use/data_miner.rb",
     "lib/earth/residence/clothes_machine_use.rb",
     "lib/earth/residence/clothes_machine_use/data_miner.rb",
     "lib/earth/residence/data_miner.rb",
     "lib/earth/residence/dishwasher_use.rb",
     "lib/earth/residence/dishwasher_use/data_miner.rb",
     "lib/earth/residence/residence_appliance.rb",
     "lib/earth/residence/residence_appliance/data_miner.rb",
     "lib/earth/residence/residence_class.rb",
     "lib/earth/residence/residence_class/data_miner.rb",
     "lib/earth/residence/residence_fuel_price.rb",
     "lib/earth/residence/residence_fuel_price/data_miner.rb",
     "lib/earth/residence/residence_fuel_type.rb",
     "lib/earth/residence/residence_fuel_type/data_miner.rb",
     "lib/earth/residence/residential_energy_consumption_survey_response.rb",
     "lib/earth/residence/residential_energy_consumption_survey_response/data_miner.rb",
     "lib/earth/shipping.rb",
     "lib/earth/shipping/carrier.rb",
     "lib/earth/shipping/carrier/data_miner.rb",
     "lib/earth/shipping/carrier_mode.rb",
     "lib/earth/shipping/carrier_mode/data_miner.rb",
     "lib/earth/shipping/data_miner.rb",
     "lib/earth/shipping/shipment_mode.rb",
     "lib/earth/shipping/shipment_mode/data_miner.rb",
     "vendor/geokit-rails/CHANGELOG.rdoc",
     "vendor/geokit-rails/MIT-LICENSE",
     "vendor/geokit-rails/README.markdown",
     "vendor/geokit-rails/Rakefile",
     "vendor/geokit-rails/about.yml",
     "vendor/geokit-rails/assets/api_keys_template",
     "vendor/geokit-rails/init.rb",
     "vendor/geokit-rails/install.rb",
     "vendor/geokit-rails/lib/geokit-rails.rb",
     "vendor/geokit-rails/lib/geokit-rails/acts_as_mappable.rb",
     "vendor/geokit-rails/lib/geokit-rails/adapters/abstract.rb",
     "vendor/geokit-rails/lib/geokit-rails/adapters/mysql.rb",
     "vendor/geokit-rails/lib/geokit-rails/adapters/postgresql.rb",
     "vendor/geokit-rails/lib/geokit-rails/adapters/sqlserver.rb",
     "vendor/geokit-rails/lib/geokit-rails/defaults.rb",
     "vendor/geokit-rails/lib/geokit-rails/geocoder_control.rb",
     "vendor/geokit-rails/lib/geokit-rails/ip_geocode_lookup.rb",
     "vendor/geokit-rails/test/acts_as_mappable_test.rb",
     "vendor/geokit-rails/test/boot.rb",
     "vendor/geokit-rails/test/database.yml",
     "vendor/geokit-rails/test/fixtures/companies.yml",
     "vendor/geokit-rails/test/fixtures/custom_locations.yml",
     "vendor/geokit-rails/test/fixtures/locations.yml",
     "vendor/geokit-rails/test/fixtures/mock_addresses.yml",
     "vendor/geokit-rails/test/fixtures/mock_families.yml",
     "vendor/geokit-rails/test/fixtures/mock_houses.yml",
     "vendor/geokit-rails/test/fixtures/mock_organizations.yml",
     "vendor/geokit-rails/test/fixtures/mock_people.yml",
     "vendor/geokit-rails/test/fixtures/stores.yml",
     "vendor/geokit-rails/test/ip_geocode_lookup_test.rb",
     "vendor/geokit-rails/test/models/company.rb",
     "vendor/geokit-rails/test/models/custom_location.rb",
     "vendor/geokit-rails/test/models/location.rb",
     "vendor/geokit-rails/test/models/mock_address.rb",
     "vendor/geokit-rails/test/models/mock_family.rb",
     "vendor/geokit-rails/test/models/mock_house.rb",
     "vendor/geokit-rails/test/models/mock_organization.rb",
     "vendor/geokit-rails/test/models/mock_person.rb",
     "vendor/geokit-rails/test/models/store.rb",
     "vendor/geokit-rails/test/schema.rb",
     "vendor/geokit-rails/test/tasks.rake",
     "vendor/geokit-rails/test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/brighterplanet/earth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Land, sky, and sea}
  s.test_files = [
    "features/automobile_make_model_year.feature",
     "features/automobile_make_year.feature",
     "features/shipment_mode.feature",
     "features/automobile_make_model_year_variant.feature",
     "features/egrid_region.feature",
     "features/automobile_make_model.feature",
     "features/automobile_fuel_type.feature",
     "features/support",
     "features/support/imports",
     "features/support/imports/automobile_make_year_bad.csv",
     "features/support/imports/bus_class_bad.csv",
     "features/support/imports/carrier_mode_bad.csv",
     "features/support/imports/automobile_make_model_year_variant_good.csv",
     "features/support/imports/egrid_region_bad.csv",
     "features/support/imports/automobile_make_model_year_bad.csv",
     "features/support/imports/automobile_fuel_type_good.csv",
     "features/support/imports/carrier_bad.csv",
     "features/support/imports/automobile_make_bad.csv",
     "features/support/imports/automobile_make_model_year_variant_bad.csv",
     "features/support/imports/automobile_size_class_good.csv",
     "features/support/imports/shipment_mode_good.csv",
     "features/support/imports/automobile_make_fleet_year_bad.csv",
     "features/support/imports/automobile_fuel_type_bad.csv",
     "features/support/imports/automobile_make_model_good.csv",
     "features/support/imports/automobile_make_model_year_good.csv",
     "features/support/imports/carrier_good.csv",
     "features/support/imports/carrier_mode_good.csv",
     "features/support/imports/egrid_subregion_bad.csv",
     "features/support/imports/automobile_make_fleet_year_good.csv",
     "features/support/imports/bus_class_good.csv",
     "features/support/imports/egrid_region_good.csv",
     "features/support/imports/shipment_mode_bad.csv",
     "features/support/imports/automobile_make_model_bad.csv",
     "features/support/imports/rail_class_bad.csv",
     "features/support/imports/automobile_make_year_good.csv",
     "features/support/imports/automobile_make_good.csv",
     "features/support/imports/automobile_size_class_bad.csv",
     "features/support/imports/egrid_subregion_good.csv",
     "features/support/imports/rail_class_good.csv",
     "features/support/env.rb",
     "features/automobile_make.feature",
     "features/bus_class.feature",
     "features/carrier_mode.feature",
     "features/automobile_size_class.feature",
     "features/rail_class.feature",
     "features/egrid_subregion.feature",
     "features/carrier.feature",
     "features/automobile_make_fleet_year.feature",
     "spec/earth_spec.rb",
     "spec/earth/air/aircraft_spec.rb",
     "spec/spec_helper.rb",
     "Gemfile",
     "Gemfile.lock"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3"])
      s.add_runtime_dependency(%q<data_miner>, ["~> 0.5.6"])
      s.add_runtime_dependency(%q<falls_back_on>, [">= 0.0.3"])
      s.add_runtime_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<cohort_scope>, [">= 0.0.7"])
      s.add_runtime_dependency(%q<conversions>, [">= 1.4.5"])
      s.add_runtime_dependency(%q<weighted_average>, [">= 0.0.4"])
      s.add_runtime_dependency(%q<loose_tight_dictionary>, [">= 0.0.8"])
      s.add_development_dependency(%q<sniff>, ["~> 0.4.11"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3"])
      s.add_dependency(%q<data_miner>, ["~> 0.5.6"])
      s.add_dependency(%q<falls_back_on>, [">= 0.0.3"])
      s.add_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_dependency(%q<cohort_scope>, [">= 0.0.7"])
      s.add_dependency(%q<conversions>, [">= 1.4.5"])
      s.add_dependency(%q<weighted_average>, [">= 0.0.4"])
      s.add_dependency(%q<loose_tight_dictionary>, [">= 0.0.8"])
      s.add_dependency(%q<sniff>, ["~> 0.4.11"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3"])
    s.add_dependency(%q<data_miner>, ["~> 0.5.6"])
    s.add_dependency(%q<falls_back_on>, [">= 0.0.3"])
    s.add_dependency(%q<geokit>, [">= 1.5.0"])
    s.add_dependency(%q<cohort_scope>, [">= 0.0.7"])
    s.add_dependency(%q<conversions>, [">= 1.4.5"])
    s.add_dependency(%q<weighted_average>, [">= 0.0.4"])
    s.add_dependency(%q<loose_tight_dictionary>, [">= 0.0.8"])
    s.add_dependency(%q<sniff>, ["~> 0.4.11"])
  end
end

