require 'earth/model'

class Recs2009Response < ActiveRecord::Base
  extend Earth::Model

  TABLE_STRUCTURE = <<-EOS
CREATE TABLE recs_2009_responses
  (
    id                         INTEGER NOT NULL PRIMARY KEY,
    weighting                  FLOAT,
    census_region_number       INTEGER,
    census_division_number     INTEGER,
    recs_grouping_id           INTEGER,
    urban_rural                CHARACTER VARYING(50),
    metro_micro                CHARACTER VARYING(50),
    climate_region_id          INTEGER,
    climate_zone_id            INTEGER,
    hdd_2009                   FLOAT,
    hdd_2009_units             CHARACTER VARYING(50),
    hdd_avg                    FLOAT,
    hdd_avg_units              CHARACTER VARYING(50),
    cdd_2009                   FLOAT,
    cdd_2009_units             CHARACTER VARYING(50),
    cdd_avg                    FLOAT,
    cdd_avg_units              CHARACTER VARYING(50),
    building_type              CHARACTER VARYING(50),
    converted_house            BOOLEAN,
    condo_coop                 CHARACTER VARYING(50),
    apartments                 INTEGER,
    year_built                 INTEGER,
    year_occupied              INTEGER,
    building_floors            INTEGER,
    levels                     INTEGER,
    area                       FLOAT,
    area_units                 CHARACTER VARYING(50),
    rooms                      INTEGER,
    bedrooms                   INTEGER,
    bathrooms                  INTEGER,
    half_baths                 INTEGER,
    other_rooms                INTEGER,
    attic_rooms                INTEGER,
    basement_rooms             INTEGER,
    shaded                     BOOLEAN,
    garage                     CHARACTER VARYING(50),
    garage_size                CHARACTER VARYING(50),
    garage_heated              BOOLEAN,
    garage_cooled              BOOLEAN,
    pool_fuel                  CHARACTER VARYING(50),
    hot_tub_fuel               CHARACTER VARYING(50),
    slab                       BOOLEAN,
    crawlspace                 BOOLEAN,
    basement                   CHARACTER VARYING(50),
    wall_material              CHARACTER VARYING(50),
    roof_material              CHARACTER VARYING(50),
    attic                      CHARACTER VARYING(50),
    windows                    INTEGER,
    window_panes               INTEGER,
    sliding_doors              INTEGER,
    insulation                 CHARACTER VARYING(50),
    drafty                     CHARACTER VARYING(50),
    high_ceiling               BOOLEAN,
    heater                     CHARACTER VARYING(50),
    heater_age                 INTEGER,
    heater_fuel                CHARACTER VARYING(50),
    heater_shared              BOOLEAN,
    heater_thermostats         INTEGER,
    heater_portion             FLOAT,
    heater_2                   CHARACTER VARYING(50),
    heater_2_fuel              CHARACTER VARYING(50),
    heater_3                   CHARACTER VARYING(50),
    heater_3_fuel              CHARACTER VARYING(50),
    heater_4                   CHARACTER VARYING(50),
    heater_4_fuel              CHARACTER VARYING(50),
    heater_5                   CHARACTER VARYING(50),
    heater_5_fuel              CHARACTER VARYING(50),
    heater_6                   CHARACTER VARYING(50),
    heater_6_fuel              CHARACTER VARYING(50),
    heater_unused              CHARACTER VARYING(50),
    heater_unused_fuel         CHARACTER VARYING(50),
    cooler_central_age         INTEGER,
    cooler_central_shared      BOOLEAN,
    cooler_acs                 INTEGER,
    cooler_ac_age              INTEGER,
    cooler_ac_energy_star      BOOLEAN,
    cooler_unused              CHARACTER VARYING(50),
    fans                       INTEGER,
    water_heater               CHARACTER VARYING(50),
    water_heater_fuel          CHARACTER VARYING(50),
    water_heater_size          CHARACTER VARYING(50),
    water_heater_age           INTEGER,
    water_heater_shared        BOOLEAN,
    water_heater_2             CHARACTER VARYING(50),
    water_heater_2_fuel        CHARACTER VARYING(50),
    water_heater_2_size        CHARACTER VARYING(50),
    water_heater_2_age         INTEGER,
    storage_water_heaters      INTEGER,
    tankless_water_heaters     INTEGER,
    lights_high_use            INTEGER,
    lights_high_use_efficient  INTEGER,
    lights_med_use             INTEGER,
    lights_med_use_efficient   INTEGER,
    lights_low_use             INTEGER,
    lights_low_use_efficient   INTEGER,
    lights_outdoor             INTEGER,
    lights_outdoor_efficient   INTEGER,
    cooking_fuel               CHARACTER VARYING(50),
    stoves                     INTEGER,
    stove_fuel                 CHARACTER VARYING(50),
    cooktops                   INTEGER,
    cooktop_fuel               CHARACTER VARYING(50),
    ovens                      INTEGER,
    oven_type                  CHARACTER VARYING(50),
    oven_fuel                  CHARACTER VARYING(50),
    outdoor_grill_fuel         CHARACTER VARYING(50),
    indoor_grill_fuel          CHARACTER VARYING(50),
    toaster                    BOOLEAN,
    coffee                     BOOLEAN,
    fridges                    INTEGER,
    fridge_type                CHARACTER VARYING(50),
    fridge_size                CHARACTER VARYING(50),
    fridge_defrost             CHARACTER VARYING(50),
    fridge_door_ice            BOOLEAN,
    fridge_age                 INTEGER,
    fridge_energy_star         BOOLEAN,
    fridge_2_type              CHARACTER VARYING(50),
    fridge_2_size              CHARACTER VARYING(50),
    fridge_2_defrost           CHARACTER VARYING(50),
    fridge_2_age               INTEGER,
    fridge_2_energy_star       BOOLEAN,
    fridge_3_type              CHARACTER VARYING(50),
    fridge_3_size              CHARACTER VARYING(50),
    fridge_3_defrost           CHARACTER VARYING(50),
    fridge_3_age               INTEGER,
    fridge_3_energy_star       BOOLEAN,
    freezers                   INTEGER,
    freezer_type               CHARACTER VARYING(50),
    freezer_size               CHARACTER VARYING(50),
    freezer_defrost            CHARACTER VARYING(50),
    freezer_age                INTEGER,
    freezer_2_type             CHARACTER VARYING(50),
    freezer_2_size             CHARACTER VARYING(50),
    freezer_2_defrost          CHARACTER VARYING(50),
    freezer_2_age              INTEGER,
    dishwasher_age             INTEGER,
    dishwasher_energy_star     BOOLEAN,
    washer                     CHARACTER VARYING(50),
    washer_age                 INTEGER,
    washer_energy_star         BOOLEAN,
    dryer_fuel                 CHARACTER VARYING(50),
    dryer_age                  INTEGER,
    tvs                        INTEGER,
    tv_size                    CHARACTER VARYING(50),
    tv_type                    CHARACTER VARYING(50),
    tv_theater                 BOOLEAN,
    tv_2_size                  CHARACTER VARYING(50),
    tv_2_type                  CHARACTER VARYING(50),
    tv_2_theater               BOOLEAN,
    tv_3_size                  CHARACTER VARYING(50),
    tv_3_type                  CHARACTER VARYING(50),
    tv_3_theater               BOOLEAN,
    computers                  INTEGER,
    computer_type              CHARACTER VARYING(50),
    computer_monitor           CHARACTER VARYING(50),
    computer_2_type            CHARACTER VARYING(50),
    computer_2_monitor         CHARACTER VARYING(50),
    computer_3_type            CHARACTER VARYING(50),
    computer_3_monitor         CHARACTER VARYING(50),
    internet                   BOOLEAN,
    printers                   INTEGER,
    fax                        BOOLEAN,
    copier                     BOOLEAN,
    well_pump                  BOOLEAN,
    engine_block_heater        BOOLEAN,
    aquarium                   BOOLEAN,
    stereo                     BOOLEAN,
    cordless_phone             BOOLEAN,
    answering_machine          BOOLEAN,
    tools                      INTEGER,
    electronics                INTEGER,
    home_business              BOOLEAN,
    home_during_week           BOOLEAN,
    telecommuting              INTEGER,
    telecommuting_units        CHARACTER VARYING(50),
    unusual_activities         BOOLEAN,
    heat_area                  FLOAT,
    heat_area_units            CHARACTER VARYING(50),
    heat_rooms                 INTEGER,
    heat_attic_portion         FLOAT,
    heat_basement_portion      FLOAT,
    heat_temp_day              FLOAT,
    heat_temp_day_units        CHARACTER VARYING(50),
    heat_temp_night            FLOAT,
    heat_temp_night_units      CHARACTER VARYING(50),
    heat_temp_away             FLOAT,
    heat_temp_away_units       CHARACTER VARYING(50),
    heat_auto_adjust_day       BOOLEAN,
    heat_auto_adjust_night     BOOLEAN,
    cool_area                  FLOAT,
    cool_area_units            CHARACTER VARYING(50),
    cool_rooms                 INTEGER,
    cool_attic_portion         FLOAT,
    cool_basement_portion      FLOAT,
    cool_temp_day              FLOAT,
    cool_temp_day_units        CHARACTER VARYING(50),
    cool_temp_night            FLOAT,
    cool_temp_night_units      CHARACTER VARYING(50),
    cool_temp_away             FLOAT,
    cool_temp_away_units       CHARACTER VARYING(50),
    cool_auto_adjust_day       BOOLEAN,
    cool_auto_adjust_night     BOOLEAN,
    cooler_central_use         CHARACTER VARYING(50),
    cooler_ac_use              CHARACTER VARYING(50),
    fan_use                    CHARACTER VARYING(50),
    humidifier_use             INTEGER,
    humidifier_use_units       CHARACTER VARYING(50),
    dehumidifier_use           INTEGER,
    dehumidifier_use_units     CHARACTER VARYING(50),
    oven_use                   INTEGER,
    oven_use_units             CHARACTER VARYING(50),
    microwave_use              CHARACTER VARYING(50),
    microwave_defrost          BOOLEAN,
    cooking_frequency          INTEGER,
    cooking_frequency_units    CHARACTER VARYING(50),
    fridge_2_use               INTEGER,
    fridge_2_use_units         CHARACTER VARYING(50),
    fridge_3_use               INTEGER,
    fridge_3_use_units         CHARACTER VARYING(50),
    dishwasher_use             INTEGER,
    dishwasher_use_units       CHARACTER VARYING(50),
    washer_use                 INTEGER,
    washer_use_units           CHARACTER VARYING(50),
    washer_temp_wash           CHARACTER VARYING(50),
    washer_temp_rinse          CHARACTER VARYING(50),
    dryer_use                  CHARACTER VARYING(50),
    tv_weekday_use             INTEGER,
    tv_weekday_use_units       CHARACTER VARYING(50),
    tv_weekend_use             INTEGER,
    tv_weekend_use_units       CHARACTER VARYING(50),
    tv_2_weekday_use           INTEGER,
    tv_2_weekday_use_units     CHARACTER VARYING(50),
    tv_2_weekend_use           INTEGER,
    tv_2_weekend_use_units     CHARACTER VARYING(50),
    tv_3_weekday_use           INTEGER,
    tv_3_weekday_use_units     CHARACTER VARYING(50),
    tv_3_weekend_use           INTEGER,
    tv_3_weekend_use_units     CHARACTER VARYING(50),
    computer_use               INTEGER,
    computer_use_units         CHARACTER VARYING(50),
    computer_idle              CHARACTER VARYING(50),
    computer_2_use             INTEGER,
    computer_2_use_units       CHARACTER VARYING(50),
    computer_2_idle            CHARACTER VARYING(50),
    computer_3_use             INTEGER,
    computer_3_use_units       CHARACTER VARYING(50),
    computer_3_idle            CHARACTER VARYING(50),
    tool_charging              CHARACTER VARYING(50),
    tool_vampires              CHARACTER VARYING(50),
    electronic_charging        CHARACTER VARYING(50),
    electronic_vampires        CHARACTER VARYING(50),
    energy_audit               BOOLEAN,
    energy_audit_year          INTEGER,
    energy_audit_incent        CHARACTER VARYING(50),
    energy_audit_incent_year   INTEGER,
    insulation_added           BOOLEAN,
    insulation_added_year      INTEGER,
    insulation_incent          CHARACTER VARYING(50),
    insulation_incent_year     INTEGER,
    windows_replaced           CHARACTER VARYING(50),
    windows_incent             CHARACTER VARYING(50),
    windows_incent_year        INTEGER,
    caulking_added             BOOLEAN,
    caulking_added_year        INTEGER,
    caulking_incent            CHARACTER VARYING(50),
    caulking_incent_year       INTEGER,
    heater_maintained          BOOLEAN,
    heater_replaced            BOOLEAN,
    heater_incent              CHARACTER VARYING(50),
    heater_incent_year         INTEGER,
    cooler_central_maintained  BOOLEAN,
    cooler_central_replaced    BOOLEAN,
    cooler_central_incent      CHARACTER VARYING(50),
    cooler_central_incent_year INTEGER,
    cooler_ac_replaced         BOOLEAN,
    cooler_ac_incent           CHARACTER VARYING(50),
    cooler_ac_incent_year      INTEGER,
    water_heater_blanket       BOOLEAN,
    water_heater_incent        CHARACTER VARYING(50),
    water_heater_incent_year   INTEGER,
    lights_replaced            BOOLEAN,
    lights_incent              CHARACTER VARYING(50),
    lights_incent_year         INTEGER,
    dishwasher_replaced        BOOLEAN,
    dishwasher_incent          CHARACTER VARYING(50),
    dishwasher_incent_year     INTEGER,
    fridge_replaced            BOOLEAN,
    fridge_incent              CHARACTER VARYING(50),
    fridge_incent_year         INTEGER,
    freezer_replaced           BOOLEAN,
    freezer_incent             CHARACTER VARYING(50),
    freezer_incent_year        INTEGER,
    washer_replaced            BOOLEAN,
    washer_incent              CHARACTER VARYING(50),
    washer_incent_year         INTEGER,
    renewable_energy           CHARACTER VARYING(50),
    own_rent                   CHARACTER VARYING(50),
    sex                        CHARACTER VARYING(50),
    employment                 CHARACTER VARYING(50),
    live_with_spouse           BOOLEAN,
    race                       CHARACTER VARYING(50),
    latino                     BOOLEAN,
    education                  CHARACTER VARYING(50),
    household_size             INTEGER,
    member_1_age               INTEGER,
    member_2_age               INTEGER,
    member_3_age               INTEGER,
    member_4_age               INTEGER,
    member_5_age               INTEGER,
    member_6_age               INTEGER,
    member_7_age               INTEGER,
    member_8_age               INTEGER,
    member_9_age               INTEGER,
    member_10_age              INTEGER,
    member_11_age              INTEGER,
    member_12_age              INTEGER,
    member_13_age              INTEGER,
    member_14_age              INTEGER,
    income                     INTEGER,
    income_employment          BOOLEAN,
    income_retirement          BOOLEAN,
    income_ssi                 BOOLEAN,
    income_welfare             BOOLEAN,
    income_investment          BOOLEAN,
    income_other               BOOLEAN,
    poverty_100                BOOLEAN,
    poverty_150                BOOLEAN,
    public_housing_authority   BOOLEAN,
    food_stamps                BOOLEAN,
    low_rent                   BOOLEAN,
    pays_electricity_heat      CHARACTER VARYING(50),
    pays_electricity_water     CHARACTER VARYING(50),
    pays_electricity_cooking   CHARACTER VARYING(50),
    pays_electricity_cool      CHARACTER VARYING(50),
    pays_electricity_lighting  CHARACTER VARYING(50),
    pays_natural_gas_heat      CHARACTER VARYING(50),
    pays_natural_gas_water     CHARACTER VARYING(50),
    pays_natural_gas_cooking   CHARACTER VARYING(50),
    pays_natural_gas_other     CHARACTER VARYING(50),
    pays_fuel_oil              CHARACTER VARYING(50),
    pays_propane               CHARACTER VARYING(50),
    electricity_heat           BOOLEAN,
    electricity_heat_2         BOOLEAN,
    electricity_cool           BOOLEAN,
    electricity_water          BOOLEAN,
    electricity_cooking        BOOLEAN,
    electricity_other          BOOLEAN,
    natural_gas_heat           BOOLEAN,
    natural_gas_heat_2         BOOLEAN,
    natural_gas_water          BOOLEAN,
    natural_gas_cooking        BOOLEAN,
    natural_gas_other          BOOLEAN,
    propane_heat               BOOLEAN,
    propane_heat_2             BOOLEAN,
    propane_water              BOOLEAN,
    propane_cooking            BOOLEAN,
    propane_other              BOOLEAN,
    fuel_oil_heat              BOOLEAN,
    fuel_oil_heat_2            BOOLEAN,
    fuel_oil_water             BOOLEAN,
    fuel_oil_other             BOOLEAN,
    kerosene_heat              BOOLEAN,
    kerosene_heat_2            BOOLEAN,
    kerosene_water             BOOLEAN,
    kerosene_other             BOOLEAN,
    wood_heat                  BOOLEAN,
    wood_heat_2                BOOLEAN,
    wood_water                 BOOLEAN,
    wood_other                 BOOLEAN,
    solar_heat                 BOOLEAN,
    solar_heat_2               BOOLEAN,
    solar_water                BOOLEAN,
    solar_other                BOOLEAN,
    other_heat                 BOOLEAN,
    other_heat_2               BOOLEAN,
    other_water                BOOLEAN,
    other_cooking              BOOLEAN,
    energy                     FLOAT,
    energy_units               CHARACTER VARYING(50),
    energy_cost                INTEGER,
    energy_cost_units          CHARACTER VARYING(50),
    electricity                FLOAT,
    electricity_units          CHARACTER VARYING(50),
    electricity_cost           INTEGER,
    electricity_cost_units     CHARACTER VARYING(50),
    natural_gas                FLOAT,
    natural_gas_units          CHARACTER VARYING(50),
    natural_gas_cost           INTEGER,
    natural_gas_cost_units     CHARACTER VARYING(50),
    propane                    FLOAT,
    propane_units              CHARACTER VARYING(50),
    propane_cost               INTEGER,
    propane_cost_units         CHARACTER VARYING(50),
    fuel_oil                   FLOAT,
    fuel_oil_units             CHARACTER VARYING(50),
    fuel_oil_cost              INTEGER,
    fuel_oil_cost_units        CHARACTER VARYING(50),
    kerosene                   FLOAT,
    kerosene_units             CHARACTER VARYING(50),
    kerosene_cost              INTEGER,
    kerosene_cost_units        CHARACTER VARYING(50),
    wood                       FLOAT,
    wood_units                 CHARACTER VARYING(50)
  );
EOS

  self.table_name = "recs_2009_responses"
  self.primary_key = "id"

  has_many :states, :foreign_key => :recs_grouping_id, :primary_key => :recs_grouping_id
end
