require 'earth/locality/census_division/data_miner'
require 'earth/locality/census_region/data_miner'
require 'earth/locality/climate_division/data_miner'
require 'earth/locality/country/data_miner'
require 'earth/locality/country_rail_traction/data_miner'
require 'earth/locality/country_rail_mode/data_miner'
require 'earth/locality/country_rail_traction_mode/data_miner'
require 'earth/locality/egrid_region/data_miner'
require 'earth/locality/egrid_subregion/data_miner'
require 'earth/locality/petroleum_administration_for_defense_district/data_miner'
require 'earth/locality/state/data_miner'
require 'earth/locality/urbanity/data_miner'
require 'earth/locality/zip_code/data_miner'

require 'earth/automobile/data_miner'
require 'earth/residence/data_miner'
