require 'earth/air/aircraft'
require 'earth/air/aircraft_class'
require 'earth/air/aircraft_fuel_use_equation'
require 'earth/air/aircraft_instance'
require 'earth/air/aircraft_instance_seat_class'
require 'earth/air/airline'
require 'earth/air/airport'
require 'earth/air/bts_aircraft'
require 'earth/air/flight_distance_class'
require 'earth/air/flight_distance_class_seat_class'
require 'earth/air/flight_seat_class'
require 'earth/air/flight_segment'

require 'earth/locality'
