require 'earth/automobile/automobile_fuel_type'
require 'earth/automobile/automobile_make'
require 'earth/automobile/automobile_make_fleet_year'
require 'earth/automobile/automobile_make_year'
require 'earth/automobile/automobile_make_model'
require 'earth/automobile/automobile_make_model_year'
require 'earth/automobile/automobile_size_class'
require 'earth/automobile/automobile_make_model_year_variant'
