require 'earth/air/data_miner'
require 'earth/automobile/data_miner'
require 'earth/bus/data_miner'
require 'earth/diet/data_miner'
require 'earth/locality/data_miner'
require 'earth/pet/data_miner'
require 'earth/rail/data_miner'
require 'earth/residence/data_miner'
