require 'earth/residence/air_conditioner_use'
require 'earth/residence/clothes_machine_use'
require 'earth/residence/dishwasher_use'
require 'earth/residence/residence_appliance'
require 'earth/residence/residence_class'
require 'earth/residence/residence_fuel_price'
require 'earth/residence/residence_fuel_type'
require 'earth/residence/residential_energy_consumption_survey_response'
