require 'earth/air/aircraft/data_miner'
require 'earth/air/aircraft_class/data_miner'
require 'earth/air/aircraft_fuel_use_equation/data_miner'
require 'earth/air/airline/data_miner'
require 'earth/air/airport/data_miner'
require 'earth/air/bts_aircraft/data_miner'
require 'earth/air/flight_distance_class/data_miner'
require 'earth/air/flight_distance_class_seat_class/data_miner'
require 'earth/air/flight_seat_class/data_miner'
require 'earth/air/flight_segment/data_miner'

require 'earth/locality/data_miner'
